/** Nazwa kraju w `world-atlas` → slug kategorii na blogu. */
export const countryCategories: Record<string, { slug: string; label: string }> = {
  Thailand: { slug: 'tajlandia', label: 'Tajlandia' },
  Philippines: { slug: 'filipiny', label: 'Filipiny' },
  Malaysia: { slug: 'malezja', label: 'Malezja' },
  Laos: { slug: 'laos', label: 'Laos' },
  Myanmar: { slug: 'birma', label: 'Birma' },
  Chile: { slug: 'chile', label: 'Chile' },
  Morocco: { slug: 'maroko', label: 'Maroko' },
  Argentina: { slug: 'argentyna', label: 'Argentyna' },
  Indonesia: { slug: 'bali', label: 'Indonezja (Bali)' },
  Vietnam: { slug: 'wietnam', label: 'Wietnam' },
  'United States of America': { slug: 'usa', label: 'USA' },
  Cambodia: { slug: 'kambodza', label: 'Kambodża' },
  Australia: { slug: 'australia', label: 'Australia' },
  Japan: { slug: 'japonia', label: 'Japonia' },
  India: { slug: 'indie', label: 'Indie' },
  Tanzania: { slug: 'tanzania', label: 'Tanzania' },
  'New Zealand': { slug: 'nowa-zelandia', label: 'Nowa Zelandia' },
  Brazil: { slug: 'brazylia', label: 'Brazylia' },
  Poland: { slug: 'polska', label: 'Polska' },
  Italy: { slug: 'wlochy', label: 'Włochy' },
  Iceland: { slug: 'islandia', label: 'Islandia' },
  'Cabo Verde': { slug: 'cabo-verde', label: 'Cabo Verde' },
  China: { slug: 'chiny', label: 'Chiny' },
  Peru: { slug: 'peru', label: 'Peru' },
  Colombia: { slug: 'kolumbia', label: 'Kolumbia' },
  Ecuador: { slug: 'ekwador', label: 'Ekwador' },
  Antarctica: { slug: 'antarktyda', label: 'Antarktyda' },
  Nepal: { slug: 'nepal', label: 'Nepal' },
  Mexico: { slug: 'meksyk', label: 'Meksyk' },
  Bolivia: { slug: 'boliwia', label: 'Boliwia' },
};

/** Kontynenty (kategorie nadrzędne na blogu) — używane w filtrach i na stronie głównej. */
export const continents = [
  { slug: 'azja', label: 'Azja' },
  { slug: 'afryka', label: 'Afryka' },
  { slug: 'ameryka-poludniowa', label: 'Ameryka Południowa' },
  { slug: 'ameryka-polnocna', label: 'Ameryka Północna' },
  { slug: 'europa', label: 'Europa' },
  { slug: 'australia-i-oceania', label: 'Australia i Oceania' },
];
